-- QUANTOS NOMES E SOBRENOMES ÚNICOS TEM NA TABELA PERSON.PERSON?

SELECT DISTINCT FirstName
FROM person.Person;

SELECT DISTINCT LastName
FROM person.Person;

SELECT DISTINCT FirstName, LastName
FROM person.Person;