-- A EQUIPE DE MARKETING PRECISA FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES
-- E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADO NO SISTEMA.

SELECT FirstName, LastName
FROM person.Person;