/*	DESAFIO 1
OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS, LISTANDO DO MAIS CARO PARA MAIS BARATO*/

SELECT TOP 10 ProductID
FROM production.Product
ORDER BY ListPrice DESC;

/*	DESAFIO 2
OBTER NOME E NUMERO DO PRODUTO DOS PRODUTOS QUE TEM PRODUCT ID ENTRE 1~4*/

SELECT TOP 4 Name, ProductNumber
FROM production.Product
ORDER BY ProductID ASC;